included:
    - Source
    - Sources
    - Tests
    - LocalPackages

excluded:
    - LocalPackages/*/.build
    - LocalPackages/*/DerivedData

opt_in_rules:
    - anyobject_protocol
    - array_init
    - contains_over_first_not_nil
    - convenience_type
    - empty_count
    - empty_string
    - explicit_init
    - fatal_error_message
    - first_where
    - for_where
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - nslocalizedstring_key
    - object_literal
    - overridden_super_call
    - prohibited_interface_builder
    - prohibited_super_call
    - reduce_into
    - redundant_type_annotation
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - vertical_whitespace_closing_braces

disabled_rules:
    - closure_parameter_position
    - comment_spacing
    - cyclomatic_complexity
    - file_length
    - force_cast
    - force_try
    - function_body_length
    - function_parameter_count
    - generic_type_name
    - identifier_name
    - large_tuple
    - line_length
    - multiple_closures_with_trailing_closure
    - nesting
    - orphaned_doc_comment
    - redundant_optional_initialization
    - redundant_type_annotation
    - todo
    - trailing_comma
    - type_body_length
    - type_name
    - trailing_closure
    - unused_capture_list
    - vertical_whitespace_opening_braces

custom_rules:
    implicit_localized_string_key:
        name: "Implicit LocalizedStringKey"
        regex: "\\b(Button|ColorPicker|DatePicker|Label|Link|Menu|NavigationLink|Picker|SecureField|Stepper|Text|TextField|Toggle)\\s*\\(\\s*(\"[^\"]+?\")"
        capture_group: 2
        message: "Use localized strings defined in Localizable.swift or StringsToLocalize.swift"
        severity: warning
    nslocalizedstring:
        name: "NSLocalizedString"
        regex: "\\bNSLocalizedString\\b"
        capture_group: 0
        match_kinds:
            - identifier
        message: "Use localized strings defined in Localizable.swift or StringsToLocalize.swift"
        severity: warning
